### ISSUE TITLE
Restructure report card?

### ISSUE THREAD

**Issue by torgo** [w3ctag/extensible-web-report-card#11]
from f2f: Should we reschedule it by layer?

**Comment by torgo** [comment]
Chaals: We should have an "expelled from school" category for e.g. appcache, websql.

**Comment by torgo** [comment]
Step 1: create a layer diagram

**Comment by travisleithead** [comment]
The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
