### ISSUE TITLE
make it clear what it is - that it's a review of existing specs

### ISSUE THREAD

**Issue by torgo** [w3ctag/extensible-web-report-card#14]
raised by @hadleybeeman

**Comment by torgo** [comment]
higher contextual level than API design guidelines

**Comment by torgo** [comment]
It's a survey; it's an example of good and bad practice; it's a survey of how we think...

**Comment by bkardell** [comment]
I think it would be good if when possible they linked to the related TAG review for more information, wdyt?

**Comment by travisleithead** [comment]
The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
