### ISSUE TITLE
mention storage

### ISSUE THREAD

**Issue by dbaron** [w3ctag/extensible-web-report-card#15]
The work at https://storage.spec.whatwg.org/ may be worth mentioning (along with the other things that it is attempting to describe).

**Comment by bkardell** [comment]
+1! that's a good one!

**Comment by travisleithead** [comment]
The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
