### ISSUE TITLE
We need broader community involvement in this document

### ISSUE THREAD

**Issue by torgo** [w3ctag/extensible-web-report-card#16]
/cc @bkardell @wycats @domenic

**Comment by torgo** [comment]
The TAG needs to be responsible for keeping it up to date but it needs to have community involvement.

**Comment by bkardell** [comment]
Yes, sorry I've been seemingly MIA... I'll start making time and seeing if we can't expand the # of people commenting...

**Comment by travisleithead** [comment]
The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
