### ISSUE TITLE
Add some idea of trend - what the trend has been

### ISSUE THREAD

**Issue by torgo** [w3ctag/extensible-web-report-card#18]
raised by @chaals.

**Comment by bkardell** [comment]
any context?  just a sort of brief state of the union overview?

**Comment by chaals** [comment]
As the document is maintained, provide a sense of whether things are getting better or not, which things are, how …

**Comment by travisleithead** [comment]
The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
