### ISSUE TITLE
Add WebASM

### ISSUE THREAD

**Issue by torgo** [w3ctag/extensible-web-report-card#19]
Need to discuss and agree how WebASM fits into this.

**Comment by travisleithead** [comment]
The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
