### ISSUE TITLE
More detail on things like CSP

### ISSUE THREAD

**Issue by torgo** [w3ctag/extensible-web-report-card#22]
@wseltzer @slightlyoff

**Comment by torgo** [comment]
What kind of API? To do what? Who should have access to that API?

**Comment by travisleithead** [comment]
The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
