### ISSUE TITLE
focus styling is disruptive in class.

### ISSUE THREAD

**Issue by bkardell** [w3ctag/extensible-web-report-card#25]
I realize that I am biased as a co-author of a proposed solution to the problem described here, but it seems that most of the standards community both understands and agrees that the problem described is real and problematic: Browsers have since 2007 (at least) been styling the focus ring with "secret information" not currently exposed to users and the :focus pseudo-class does not consult the same source of truth creating a bad conflict of benefit/reward/ability to comprehend the problem and this is currently hurting a whole lot of sites a11y.

Described in more detail http://radar.oreilly.com/2015/08/proposing-css-input-modailty.html

**Comment by travisleithead** [comment]
This feedback can perhaps be added to our general design-reviews issue on a11y?

The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
