### ISSUE TITLE
In General, how can we show positive movement?

### ISSUE THREAD

**Issue by torgo** [w3ctag/extensible-web-report-card#27]
How can we indicate visually somehow when a particular spec or technology has improved and that it's on a good track? @bkardell

**Comment by torgo** [comment]
Something like positive momentum, negative momentum, stalled?

**Comment by travisleithead** [comment]
Nope

---

The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
