### ISSUE TITLE
Better contribution explanation

### ISSUE THREAD

**Issue by torgo** [w3ctag/extensible-web-report-card#28]
Also in discussion with @bkardell – We need to have a clearer explanation to would-be contributors of how to get involved here. How can you submit a suggested addition to the report? Etc...  Assigning this to me to try to write something up.

**Comment by travisleithead** [comment]
The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
