### ISSUE TITLE
Object.observe mentions?

### ISSUE THREAD

**Issue by bkardell** [w3ctag/extensible-web-report-card#29]
Object.observe() is mentioned a few times on the report card, but it would appear to have fallen out of favor before it got wide implementation.  I think that requires discussion/comment (or perhaps at least removal of existing comments?)

**Comment by travisleithead** [comment]
The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
