### ISSUE TITLE
Flesh out parts that are pretty sparse

### ISSUE THREAD

**Issue by domenic** [w3ctag/extensible-web-report-card#3]
Especially with more links, but in general certain parts are "telegraphic" as @torgo puts it.

**Comment by torgo** [comment]
E.g. "Service worker!" - maybe @slightlyoff could add some verbiage here?

**Comment by travisleithead** [comment]
The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
