### ISSUE TITLE
SRI?

### ISSUE THREAD

**Issue by bkardell** [w3ctag/extensible-web-report-card#30]
SRI is CR and appears to have support in chrome 45, ff 43 and opera 32 - TAG discussed this a while back IIRC because I brought it up.  Should we toss it on here with comment?  Might be decent to do while @diracdeltas is still on TAG?

**Comment by travisleithead** [comment]
See also: https://github.com/w3ctag/design-reviews/issues/186
---
The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to individual spec issues if needed.

Apologies for the delay. Thanks for flying TAG.
