### ISSUE TITLE
SVG?

### ISSUE THREAD

**Issue by torgo** [w3ctag/extensible-web-report-card#7]
Considering the [new SVG charter](http://www.w3.org/Graphics/SVG/2014/charter) under consideration it seems like we should consider where SVG sits and what we'd like to see happen to make it more extensible.

**Comment by travisleithead** [comment]
The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
