### ISSUE TITLE
Web RTC?

### ISSUE THREAD

**Issue by bkardell** [w3ctag/extensible-web-report-card#8]
It has wider implementations than some other things on the report card already... Could probably use an evaluation.  

http://caniuse.com/#search=webrtc

**Comment by travisleithead** [comment]
The TAG has decided to no longer maintain the extensible web report card. Instead of addressing these issues in this document, major issues should be re-raised on the http://github.com/w3ctag/design-reviews repo; other feedback may be added to the individual (original) specs if needed.

Apologies for the delay. Thanks for flying TAG.
